[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "BjxTZ4PvZToviX8JfNaxUwf45mhkLMp3x656tdfcuCRS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/johnathandoan/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
